AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/cygport/**/*'
    - 'vendor/**/*'

Layout/IndentHeredoc:
  EnforcedStyle: active_support

Metrics/AbcSize:
  Max: 40
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 35
Metrics/ParameterLists:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 12

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false
