require: rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'spec/cygport/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 40
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 35
Metrics/ParameterLists:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 12

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false
