plugins: rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - 'spec/cygport/**/*'
    - 'vendor/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 45
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 35
Metrics/ParameterLists:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 12

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false
