# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Init & update submodule
          command: |
            git submodule init
            git submodule update
            git submodule foreach git pull origin master

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ .Branch }}
          # fallback to using the latest cache if no exact match is found
          #- v1-dependencies-

      - run:
          name: Show ruby version
          command: |
            ruby -v

      - run:
          name: Install native libraries
          command: |
            sudo apt-get install cmake libicu-dev

      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v2-dependencies-{{ .Branch }}

      # Rubocop
      - run:
          name: Rubocop
          command: |
            bundle exec rubocop -D -c .rubocop.yml --format simple

      # Fasterer
      - run:
          name: Fasterer
          command: |
            bundle exec fasterer

      # Run tests
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --no-color \
                            --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml

      # Collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage
