
require 'xezat/command/dist'

class DistTest < Test::Unit::TestCase

  include Xezat
  
  def test_get_ini
    parent = File.dirname(File.dirname(__FILE__))
    hints = HintManager.new(File.join(parent, 'fixture', 'hint'))
    dist = Dist.new
    timestamp = Time.now.to_i
    content = dist.get_ini(hints, timestamp)
    assert_equal(<<EOL, content)
# This file is automatically generated.  If you edit it, your
# edits will be discarded next time the file is generated.
# See http://cygwin.com/setup.html for details.
#
setup-timestamp: #{timestamp}

@ aaa
sdesc: "aaa (licensing & readmes)"
ldesc: "aaaaaa"
category: Libs
requires: cygwin libaaa0
version: 0.0.0-1
install: x86/release/aaa/aaa-0.0.0-1.tar.bz2 198 c71705507ce8d961595bcd128185c61b
source: x86/release/aaa/aaa-0.0.0-1-src.tar.bz2 209 b9cf561f835f6a4d21fa46bcb40bd35a

@ bbb
sdesc: "bbb"
ldesc: "bbbbbb"
category: X11
requires: cygwin
version: 0.0.0-1
install: x86/release/bbb/bbb-0.0.0-1.tar.bz2 197 4acc32e7d4202c07937a99129136eb5f
source: x86/release/bbb/bbb-0.0.0-1-src.tar.bz2 207 b2b691d61542bd67b009280f95fce5c2

@ libaaa-devel
sdesc: "aaa (development)"
ldesc: "aaaaaa"
category: Libs
requires: cygwin libaaa0
version: 0.0.0-1
install: x86/release/aaa/libaaa-devel/libaaa-devel-0.0.0-1.tar.bz2 211 21a8c08754e01eb6349152183ccfe302
source: x86/release/aaa/aaa-0.0.0-1-src.tar.bz2 209 b9cf561f835f6a4d21fa46bcb40bd35a

@ libaaa0
sdesc: "aaa (runtime)"
ldesc: "aaaaaa"
category: Libs
requires: cygwin
version: 0.0.0-1
install: x86/release/aaa/libaaa0/libaaa0-0.0.0-1.tar.bz2 205 f8f035e2da5743ce03dbbb334ccd8fe4
source: x86/release/aaa/aaa-0.0.0-1-src.tar.bz2 209 b9cf561f835f6a4d21fa46bcb40bd35a

EOL
  end
  
end
